version: '3.8'

services:
  web:
    container_name: tree_web
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint:
      sh -c "python /code/manage.py migrate &&
      python /code/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - .env
