# Generated by Django 4.1.7 on 2023-03-24 12:00
import os

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth.models import User

        DJANGO_SU_NAME = os.environ.get('DJANGO_SUPERUSER_USERNAME')
        DJANGO_SU_EMAIL = os.environ.get('DJANGO_SUPERUSER_EMAIL')
        DJANGO_SU_PASSWORD = os.environ.get('DJANGO_SUPERUSER_PASSWORD')

        superuser = User.objects.create_superuser(
            username=DJANGO_SU_NAME,
            email=DJANGO_SU_EMAIL,
            password=DJANGO_SU_PASSWORD,
            last_login='2023-03-24 11:44',
        )

        superuser.save()

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                (
                    'id', models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=50, blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name='children', to='menu.menu')),
                ('order', models.IntegerField(blank=True)),
            ],
        ),
        migrations.RunPython(generate_superuser),
    ]
